### ISSUE TITLE
Does controller watch the existing objects as well?

### ISSUE THREAD

**Issue by smartaquarius10** [leovct/kube-operator-tutorial#1]
Hello,

If we restart a controller, does it still watch the existing objects or reconciliation happens while creating a new object only. 

If not, is there any way to force reconciliation on restart of controller.

Thank you

**Comment by leovct** [comment]
> Hello,
> 
> 
> 
> If we restart a controller, does it still watch the existing objects or reconciliation happens while creating a new object only. 
> 
> 
> 
> If not, is there any way to force reconciliation on restart of controller.
> 
> 
> 
> Thank you

That's a great question! Yes, the controller will watch the existing objects as well as the new ones. You can either restart or even delete and re-create the controller, the controller will still watch existing objects.

**Comment by smartaquarius10** [comment]
@leovct Thank you so much 😃

**Comment by smartaquarius10** [comment]
@leovct, Do we have to specifically write any code for that, or reconciliation happens on its own with restart of controller.

**Comment by leovct** [comment]
> @leovct, Do we have to specifically write any code for that, or reconciliation happens on its own with restart of controller. 

You don't need to write any code for that. Actually what happens is that when you restart the controller, for every existing custom resource (that your controller is responsible for), it will trigger a creation event and thus a reconciliation loop. It's possible to filter these events later if you don't want this kind of behaviour and that's a topic I want to explore in my next article 😊

**Comment by smartaquarius10** [comment]
@leovct , Oh ok. Thank you so much. One small query.. Getting this error while running  `make manifests`
`/bin/controller-gen: Permission denied`
Any suggestions please?

**Comment by leovct** [comment]
> @leovct , Oh ok. Thank you so much. One small query.. Getting this error while running  `make manifests`
> 
> `/bin/controller-gen: Permission denied`
> 
> Any suggestions please?

Your welcome! 🙂

Check the permissions of the _controller-gen_ binary, you might need to run something like `chmod +x /bin/controller-gen`.
